name: Matrix Job Output

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [foo, bar, baz]
    steps:
      - name: exec
        run: |
          version="${{ matrix.version }}"
          if [ "$version" = "foo" ]; then
            echo "foo, will fail"
            exit 23
          elif [ "$version" = "baz" ]; then
            echo "baz, will sleep"
            sleep 2m
            exit 0
          else
            echo "will success"
            exit 0
          fi

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    if: ${{ needs.job1.result == 'success' || needs.job1.result == 'failure' || needs.job1.result == 'cancelled' || needs.job1.result == 'skipped' }}
    steps:
      - run: echo '${{ needs.job1.result }}'
